apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tekton-app
  template:
    metadata:
      labels:
        app: tekton-app
    spec:
      containers:
        - name: hello-world
          image: docker.io/sathish404/latha
          ports:
            - containerPort: 3000
